import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "flowbite";
import './globals.css'
import { Layout } from "@/core/components/Layout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GYMBRO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es-MX" className="dark">
      <body className={inter.className + " bg-light dark:bg-dark"}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
